// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WololoPrueba.DbContexts;

#nullable disable

namespace WololoPrueba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230927014522_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WololoPrueba.Models.Civ", b =>
                {
                    b.Property<int>("CivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CivId"), 1L, 1);

                    b.Property<string>("CivName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CivId");

                    b.ToTable("LasCivs");
                });
#pragma warning restore 612, 618
        }
    }
}
